// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: proto/gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_Login_FullMethodName         = "/gateway.GatewayService/Login"
	GatewayService_Register_FullMethodName      = "/gateway.GatewayService/Register"
	GatewayService_CreateProduct_FullMethodName = "/gateway.GatewayService/CreateProduct"
	GatewayService_UpdateProduct_FullMethodName = "/gateway.GatewayService/UpdateProduct"
	GatewayService_DeleteProduct_FullMethodName = "/gateway.GatewayService/DeleteProduct"
	GatewayService_CreateOrder_FullMethodName   = "/gateway.GatewayService/CreateOrder"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	// Auth-service
	Login(ctx context.Context, in *GatewayLoginReq, opts ...grpc.CallOption) (*GatewayLoginResp, error)
	Register(ctx context.Context, in *GatewayRegisterReq, opts ...grpc.CallOption) (*GatewayRegisterResp, error)
	// Product-service
	CreateProduct(ctx context.Context, in *GatewayCreateProductReq, opts ...grpc.CallOption) (*GatewayCreateProductResp, error)
	UpdateProduct(ctx context.Context, in *GatewayUpdateProductReq, opts ...grpc.CallOption) (*GatewayUpdateProductResp, error)
	DeleteProduct(ctx context.Context, in *GatewayDeleteProductReq, opts ...grpc.CallOption) (*GatewayDeleteProductResp, error)
	// Order-service
	CreateOrder(ctx context.Context, in *GatewayOrderCreateReq, opts ...grpc.CallOption) (*GatewayOrderCreateResp, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) Login(ctx context.Context, in *GatewayLoginReq, opts ...grpc.CallOption) (*GatewayLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayLoginResp)
	err := c.cc.Invoke(ctx, GatewayService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Register(ctx context.Context, in *GatewayRegisterReq, opts ...grpc.CallOption) (*GatewayRegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayRegisterResp)
	err := c.cc.Invoke(ctx, GatewayService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CreateProduct(ctx context.Context, in *GatewayCreateProductReq, opts ...grpc.CallOption) (*GatewayCreateProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayCreateProductResp)
	err := c.cc.Invoke(ctx, GatewayService_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) UpdateProduct(ctx context.Context, in *GatewayUpdateProductReq, opts ...grpc.CallOption) (*GatewayUpdateProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayUpdateProductResp)
	err := c.cc.Invoke(ctx, GatewayService_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteProduct(ctx context.Context, in *GatewayDeleteProductReq, opts ...grpc.CallOption) (*GatewayDeleteProductResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayDeleteProductResp)
	err := c.cc.Invoke(ctx, GatewayService_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CreateOrder(ctx context.Context, in *GatewayOrderCreateReq, opts ...grpc.CallOption) (*GatewayOrderCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayOrderCreateResp)
	err := c.cc.Invoke(ctx, GatewayService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	// Auth-service
	Login(context.Context, *GatewayLoginReq) (*GatewayLoginResp, error)
	Register(context.Context, *GatewayRegisterReq) (*GatewayRegisterResp, error)
	// Product-service
	CreateProduct(context.Context, *GatewayCreateProductReq) (*GatewayCreateProductResp, error)
	UpdateProduct(context.Context, *GatewayUpdateProductReq) (*GatewayUpdateProductResp, error)
	DeleteProduct(context.Context, *GatewayDeleteProductReq) (*GatewayDeleteProductResp, error)
	// Order-service
	CreateOrder(context.Context, *GatewayOrderCreateReq) (*GatewayOrderCreateResp, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) Login(context.Context, *GatewayLoginReq) (*GatewayLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGatewayServiceServer) Register(context.Context, *GatewayRegisterReq) (*GatewayRegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGatewayServiceServer) CreateProduct(context.Context, *GatewayCreateProductReq) (*GatewayCreateProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedGatewayServiceServer) UpdateProduct(context.Context, *GatewayUpdateProductReq) (*GatewayUpdateProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteProduct(context.Context, *GatewayDeleteProductReq) (*GatewayDeleteProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedGatewayServiceServer) CreateOrder(context.Context, *GatewayOrderCreateReq) (*GatewayOrderCreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Login(ctx, req.(*GatewayLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Register(ctx, req.(*GatewayRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayCreateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateProduct(ctx, req.(*GatewayCreateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayUpdateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).UpdateProduct(ctx, req.(*GatewayUpdateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayDeleteProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteProduct(ctx, req.(*GatewayDeleteProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayOrderCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateOrder(ctx, req.(*GatewayOrderCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _GatewayService_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _GatewayService_Register_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _GatewayService_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _GatewayService_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _GatewayService_DeleteProduct_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _GatewayService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gateway.proto",
}
